{.$DEFINE DEBUG_OPTIMIZATION}

{$DEFINE TEST}


{$DEFINE OPTIMIZE_CALLFUNCTIONS_MDL}       {5% in with no antialing... }
{$DEFINE OPTIMIZE_CALLFUNCTIONS_CP_ADD}    { ...and filling }
{$DEFINE OPTIMIZE_CALLFUNCTIONS}           {very very litle}
{$DEFINE OPTIMIZE_GLYPHPOLYGONE_STORAGE}   {2% in Filling mode- 20% without filling mode}

{-------------
for my debug and development :}

{$DEFINE TEST_NORMALIZED_SPLINE}


